title: Yuxin Jin Homepage
page-top-title: Yuxin Jin Homepage
top-section-bg-text: Life is like a sea, only a strong-willed person can reach the other side of life.
home-subtitle: Yuxin Jin
copyright-text: '&copy; 2026 Yuxin Jin. All Rights Reserved. Template by Jerry Yin, based on <a href="https://github.com/JerryYin777/JerryYin777.github.io">this repo</a>.'